"""Initial migration.

Revision ID: 1f67be70656c
Revises: 
Create Date: 2022-07-25 16:11:52.079215

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '1f67be70656c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    user_table = op.create_table('user',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('email', sa.VARCHAR(length=254), nullable=False),
                    sa.Column('password_hash', sa.CHAR(length=64), nullable=False),
                    sa.Column('password_salt', sa.CHAR(length=16), nullable=False),
                    sa.Column('created', sa.TIMESTAMP(), nullable=True),
                    sa.Column('updated', sa.TIMESTAMP(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email')
                    )
    category_table = op.create_table('category',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('created', sa.TIMESTAMP(), nullable=True),
                    sa.Column('updated', sa.TIMESTAMP(), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    item_table = op.create_table('item',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
                    sa.Column('description', sa.TEXT, nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('category_id', sa.Integer(), nullable=False),
                    sa.Column('created', sa.TIMESTAMP(), nullable=True),
                    sa.Column('updated', sa.TIMESTAMP(), nullable=True),
                    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item')
    op.drop_table('category')
    op.drop_table('user')
    # ### end Alembic commands ###
