"""empty message

Revision ID: 451cd0c7e656
Revises: 7b01b568b078
Create Date: 2023-01-12 16:05:16.884965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '451cd0c7e656'
down_revision = '7b01b568b078'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_key', sa.String(length=255), nullable=False),
    sa.Column('application_secret', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('application')
    # ### end Alembic commands ###
